# Generated by Django 5.1.4 on 2024-12-09 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nit_ci', models.CharField(max_length=50)),
                ('f_nacimiento', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='automoviles',
            name='precio',
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.automoviles')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.clientes')),
            ],
        ),
    ]
